server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : employee-service
          url: lb://employee-service
          predicates:
            - Path=/employee/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



management:
  tracing:
    sampling:
      probability: 1.0